name: Build Vite App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create public_html zip
        run: |
          cd dist
          zip -r ../public_html.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: public_html
          path: public_html.zip
